"""crear tablas

Revision ID: 418fc49278c9
Revises: 
Create Date: 2026-03-17 23:32:24.330750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418fc49278c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('clave', sa.String(length=10), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_table('servicios_adicionales',
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.Column('nombre_servicio', sa.String(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=False),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_servicio')
    )
    op.create_table('tipo_habitacion',
    sa.Column('id_tipo', sa.UUID(), nullable=False),
    sa.Column('nombre_tipo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=False),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tipo')
    )
    op.create_table('habitacion',
    sa.Column('id_habitacion', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('id_tipo', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=False),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo'], ['tipo_habitacion.id_tipo'], ),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_habitacion'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('reserva',
    sa.Column('id_reserva', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_habitacion', sa.UUID(), nullable=True),
    sa.Column('fecha_entrada', sa.Date(), nullable=True),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('estado_reserva', sa.String(), nullable=True),
    sa.Column('numero_de_personas', sa.Integer(), nullable=True),
    sa.Column('noches', sa.Integer(), nullable=True),
    sa.Column('costo_total', sa.Float(), nullable=True),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=False),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_edicion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_habitacion'], ['habitacion.id_habitacion'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_table('reserva_servicios',
    sa.Column('id_reserva', sa.UUID(), nullable=False),
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_reserva'], ['reserva.id_reserva'], ),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios_adicionales.id_servicio'], ),
    sa.PrimaryKeyConstraint('id_reserva', 'id_servicio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva_servicios')
    op.drop_table('reserva')
    op.drop_table('habitacion')
    op.drop_table('tipo_habitacion')
    op.drop_table('servicios_adicionales')
    op.drop_table('usuario')
    # ### end Alembic commands ###